name: continuous-integration/github-actions/

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [1.8, 11]

    runs-on: ${{ matrix.platform }}
    name: on ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Build with Maven
      run: mvn -V clean verify --file pom.xml  -Djenkins.test.timeout=5000
